### ISSUE TITLE
Error in minio admin module

### ISSUE THREAD

**Issue by lillie-dae** [Project-MONAI/monai-deploy-workflow-manager#225]
### Description
Neil is receiving following error...

Unknown Error System.Linq.Enumerable+SelectManySingleSelectorIterator`2[System.String,System.Char]
stack trace

   at Monai.Deploy.Storage.MinIO.StorageAdminService.<Execute>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Monai.Deploy.Storage.MinIO.StorageAdminService.<UserAlreadyExistsAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Monai.Deploy.Storage.MinIO.StorageAdminService.<CreateUserAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Monai.Deploy.WorkflowManager.TaskManager.TaskManager.<AddCredentialsToPlugin>d__27.MoveNext() in C:\Users\NeilSouth\source\repos\monai-deploy-workflow-manager\src\TaskManager\TaskManager.cs:line 306
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Monai.Deploy.WorkflowManager.TaskManager.TaskManager.<HandleDispatchTask>d__26.MoveNext() in C:\Users\NeilSouth\source\repos\monai-deploy-workflow-manager\src\TaskManager\TaskManager.cs:line 249

### Steps to reproduce
Please share a clear and concise description of the problem.
2. Install '....'
3. Run commands '....'
...

### Actual behavior
A clear and concise description of what actually happened.

### Configuration

* Workflow Manager version/commit:
* OS and version (distro if applicable):
* Kubernetes version (if applicable):
* Docker version (if applicable):
* Installation source (NGC, Dockerhub, or something else):
* Hardware configuration (CPU, GPU, memory, storage, etc...):

### Regression?
Did this work in the previous build or release of the Workflow Manager? If you can try a previous release or build to find out, that can help us narrow down the problem. If you don't know, that's OK.

### Other information
(Please attach any logs available and remember to anonymize any PHI before sharing).

**Comment by neildsouth** [comment]
add the mc.exe to the project (maybe in a folder in the root of the project called something like externalDepends) and flag it to copy to output directory.
then write some integration tests for the CreateUserAsync funtionality

**Comment by lillie-dae** [comment]
Notes: (2 issues)
SetConnection command has been lost in PRs. this will need to be replemented.
exception return types needs to be improved its logging out object type rather than the actual string.
